version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_NAME: "Test_Project_MERN_Stack"
      DB_USER: "root"
      DB_PASS: "Amitdogra"
      DB_HOST: "127.0.0.1"
      EXTENSION: mysql
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "Test_Project_MERN_Stack" 
      MYSQL_USER: root
      MYSQL_PASSWORD: Amitdogra
      MYSQL_ROOT_PASSWORD: Amitdogra
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
